package me.voleia.volands.SkillTree;

public enum InvIcon {
    BACKGROUND,DOWN_STRAIGHT,DOWN_FROM_RIGHT,DOWN_FROM_LEFT,STRAIGHT_ACROSS,T,INCOMP_STRAIGHT_ACROSS,ACTIVE_UNLOCKED,ACTIVE_AVAILIBLE,ACTIVE_EXPENSIVE,ACTIVE_LOCKED,PASSIVE_UNLOCKED,PASSIVE_AVAILIBLE,PASSIVE_EXPENSIVE,PASSIVE_LOCKED,TOGGLE_UNLOCKED,TOGGLE_AVAILIBLE,TOGGLE_EXPENSIVE,TOGGLE_LOCKED,ARROW_UP,ARROW_DOWN,ARROW_LEFT,ARROW_RIGHT
}
